### DISCUSSION TITLE
Permissions required for read/write in client AutoScallingV2

### DISCUSSION THREAD

**Discussion by teknolog2k** [kubernetes-client/csharp#1510] [Q&A]
Hi, 

Our general permissions work well for the client. I am able to fetch configuration and delete it. However,  we are adding the functionality to delete and remake/restart autoscaller (the horizontal one, hpa). How do I know which permissions are needed to add?

**Comment by tg123** [comment]
check out the apiGroups and resources of the what wish to write and add them to your role
for example, `kubectl get no`  is using apiGoup "" and resource nodes

```
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "update"]
```
