### ISSUE TITLE
Support round-trip serialization of CRDs

### ISSUE THREAD

**Issue by stan-sz** [kubernetes-client/csharp#1032]
Currently, the Yaml deserializer is configured to convert all property types to strings. After https://github.com/aaubry/YamlDotNet/pull/699, it is now possible to deserialize `bool`s and decimals with their types.

E.g.

```yaml
apiVersion: foo.bar/v1alpha
kind: Foo
metadata:
  name: foo
  namespace: ns
spec:
  bool: false
  byte: 123
  float: 12.3
```

A call to `KubernetesYaml.Deserialize` and `KubernetesYaml.Serialize` will emit:

```yaml
apiVersion: foo.bar/v1alpha
kind: Foo
metadata:
  name: foo
  namespace: ns
spec:
  bool: "false"
  byte: "123"
  float: "12.3"
```
