### ISSUE TITLE
RBAC inside cluster

### ISSUE THREAD

**Issue by RouR** [kubernetes-client/csharp#105]
I try to use this client inside CronJob

It is work in minikube, and does not work in real cluster with RBAC

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tool-dockercheck-serviceaccount
  namespace: dev

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: tool-dockercheck-role
rules:
    - apiGroups: [""] 
      # "" indicates the core API group
      resources: ["deployments", "namespaces"]
      verbs: ["get", "list", "update", "patch"]
  

  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tool-dockercheck-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tool-dockercheck-role
subjects:
  - kind: ServiceAccount
    name: tool-dockercheck-serviceaccount
    namespace: dev

---


apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tool-dockercheck-cron
  namespace: dev
  labels:
    app: tool-dockercheck
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3  
  
  jobTemplate:
      spec:                  
          template:
            metadata:
              namespace: dev
              labels:
                app: tool-dockercheck   
                ci: someDataForOverride
            spec:
              serviceAccountName: tool-dockercheck-serviceaccount
              restartPolicy: Never               
              containers:
              - name: tool-dockercheck
                image: roured/tdtb-dockercheck:dev
                imagePullPolicy: Always
                env:
                - name: KUBERNETES_NAMESPACE
                  value: "dev"
                - name: LABEL
                  value: "ci"
                

```

This [code](https://github.com/RouR/ToDo-ToBuy/blob/dev/src/DockerHubChecker/Program.cs#L29)
```
var config = KubernetesClientConfiguration.InClusterConfig();
IKubernetes client = new Kubernetes(config);
client.ListNamespacedDeployment(k8Namespace)

```

throw 

> Unhandled Exception: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'

I think that there is a mistake in the configuration or a bug in the client itself.

It would be good to make the message about the error more informative. For example, what kind of role is needed.

**Comment by tg123** [comment]
copy from #58

Azure/autorest#931 (comment)

**Comment by brendandburns** [comment]
If you see that comment it should provide a way to get more detail.

Do you believe you are getting `Forbidden` as the result of an error?  If so, can you please send more details about your kubeconfig (please anonymize it first)

**Comment by RouR** [comment]
Sorry, I don`t understand how to get more details.

All my configs is here https://github.com/RouR/ToDo-ToBuy/tree/dev/k8s

**Comment by tg123** [comment]
Detailed message from k8s api server should be in
HttpOperationException.Response.Content

example might be helpful

```
catch (Microsoft.Rest.HttpOperationException httpOperationException)
                    {
                        var phase = httpOperationException.Response.ReasonPhrase; 
//Bad Request
                        var content = httpOperationException.Response.Content; 
// {"error":{"code":"InvalidRequest","message":"Invalid dataset. This API can only be called on a DirectQuery dataset"}}
                        throw new  PowerBIException(content );
                    }
```

**Comment by RouR** [comment]
> {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.apps is forbidden: User \"system:serviceaccount:dev:tool-dockercheck-serviceaccount\" cannot list deployments.apps in the namespace \"dev\"","reason":"Forbidden","details":{"group":"apps","kind":"deployments"},"code":403}

I fix this issue by add apiGroups: ["apps"] 

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: tool-dockercheck-role
rules:
    - apiGroups: ["", "apps"] 
      # "" indicates the core API group
      resources: ["deployments", "namespaces"]
      verbs: ["get", "list", "update", "patch"]
```

Can be closed.

Maybe add httpOperationException.Response.Content to exception message by default?
