### ISSUE TITLE
Calls to configure Kubernetes client hang (i.e. BuildConfigFromConfigFile) due to Verbose logging in kube config for AWS External Authentication

### ISSUE THREAD

**Issue by siparsons** [kubernetes-client/csharp#1092]
Describe the bug
Activating verbose logging of the AWS console causes the following line of code to hang:

https://github.com/kubernetes-client/csharp/blob/48b5ea6de09de8aa9bd2a54256efd2a252e6e151/src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs#L559

Kubernetes C# SDK Client Version
8.0.68

Server Kubernetes Version
e.g. 1.24.2

Dotnet Runtime Version
.Net core

To Reproduce
I have the following local Kube config setting (see section below). Note that this is allowing the user token to be retrieved from an external authentication provider - AWS Client Console in this case. 

When using AWS console it is sometimes necessary to turn on "Verbose Logging" of the console application to diagnose connection issues. This is done by including the additional "--debug" command line argument seen below. 

```
users:
- name: arn:aws:eks:eu-west-xxxxxxxxxxxxxxx:cluster/xxxxxxxxxxxxxxx
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-2
      - eks
      - get-token
      - --cluster-name
      - xxxxxxxxxxxxxxx
      - --debug
      command: aws
      env:
      - name: AWS_PROFILE
        value: xxxxxxxxxxxxxxx
      interactiveMode: IfAvailable
      provideClusterInfo: false
``` 

The effect of this is twofold.

1. The console/process output is verbose (as one might expect)
2. The console/process output includes far more than just the final JSON response relied on by the kubernetes-client library

The response result has no paging information
Expect  call to KubernetesClientConfiguration.BuildConfigFromConfigFile() to return a valid client, rather than hang.

Suggested fix. 

The immediate "hanging" problem would appear to be due to the verbose nature of the stdout when starting the process.

This is because the process response is being called Synchronously. 

Instad use the following approach to retrieve the full output from the process:

```
process.Start();
process.BeginOutputReadLine();
process.BeginErrorReadLine();

var stdout = "";
var stderr = "";

process.OutputDataReceived += (sender, args) =>
{
    stdout += args.Data;
};
process.ErrorDataReceived += (sender, args) =>
{
    stderr += args.Data;
};

process.WaitForExit();

```

The second challenge will be to extract the required JSON response from the output. This can be done with a relatively simple REGEX prior to https://github.com/kubernetes-client/csharp/blob/48b5ea6de09de8aa9bd2a54256efd2a252e6e151/src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs#L571

```
var exp = new Regex("(?ismx)(?<json>{\".+\"}+)\\s*$");
stdout = exp.Match(stdout).Groups["json"].Value;
```
