### ISSUE TITLE
User: X does not have appropriate auth credentials in kubeconfig

### ISSUE THREAD

**Issue by tzachiabo** [kubernetes-client/csharp#1113]
**Describe the bug**
I am trying to connect to an AKS cluster using the sample code described in the readme
My AKS cluster have rbac enabled and AAD authentication with Azure RBAC
but I keep getting `User: X does not have appropriate auth credentials in kubeconfig`
On a different cluster with "Local accounts with Kubernetes RBAC" everything is working properly

**Kubernetes C# SDK Client Version**
9.0.38

**Server Kubernetes Version**
1.23.12

**Dotnet Runtime Version**
.net6

**To Reproduce**
use the sample code to connect to a k8s cluster:
`
var azure = Microsoft.Azure.Management.Fluent.Azure
                .Authenticate(credentials)
                .WithSubscription(aksResource.SubscriptionId);

            var kubeConfigBytes = azure.KubernetesClusters.GetUserKubeConfigContents(
                aksResource.ResourceGroup,
                aksResource.Resource
            );

var kubeConfigRaw = KubernetesClientConfiguration.LoadKubeConfig(new MemoryStream(kubeConfigBytes));
var kubeConfig = KubernetesClientConfiguration.BuildConfigFromConfigObject(kubeConfigRaw);
var client = new Kubernetes(kubeConfig)
`

**Expected behavior**
k8s client object with no error

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: Windows
 - Environment N/A
 - Cloud Azure

**Additional context**

**Comment by tg123** [comment]
could you please `az aks get-credentials --resource-group <rg> --name <name> -f -`
to check what is inside the `users ` section?

it should be something like below
```
users:
- name: xxxxxx
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - xxxxx
      - --client-id
      - xxxx
      - --tenant-id
      - xxxxx
      - --login
      - devicecode
      command: kubelogin
      env: null
      provideClusterInfo: false
```


azure rbac calls <https://github.com/Azure/kubelogin> to login
but your err is likely due to no user context generated correctly
