### ISSUE TITLE
X509Certificate Exception with BuildConfigFromConfigFile

### ISSUE THREAD

**Issue by dontspeak** [kubernetes-client/csharp#1303]
I have a .kubeconfig file that is perfectly working when I use kubectl via windows command line or powershell.

But when I try to initialize

`var config = KubernetesClientConfiguration.BuildConfigFromConfigFile(configFile);`

I immediately get an exception "Object not found" with following stacktrace. 

**How can I solve that? Thank you.**

   _bei Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(ReadOnlySpan1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   bei System.Security.Cryptography.X509Certificates.X509Certificate..ctor(ReadOnlySpan1 data)
   bei k8s.KubernetesClientConfiguration.SetClusterDetails(K8SConfiguration k8SConfig, Context activeContext)
   bei k8s.KubernetesClientConfiguration.InitializeContext(K8SConfiguration k8SConfig, String currentContext)
   bei k8s.KubernetesClientConfiguration.GetKubernetesClientConfiguration(String currentContext, String masterUrl, K8SConfiguration k8SConfig)
   bei k8s.KubernetesClientConfiguration.<BuildConfigFromConfigFileAsync>d__19.MoveNext()
   bei k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)_

**Comment by dontspeak** [comment]
Sorry for delay, will answer quikly now.

How do you mean that, "embed cert" ?

**Comment by dontspeak** [comment]
Anyone?

**Comment by tg123** [comment]
embed:
`    certificate-authority-data: LS0tLS1CRUdJT......`

non-embed
` client-certificate: client.crt`

**Comment by dontspeak** [comment]
Hi, its already embedded. Here is the cubeconfig Im using, with all names and ip replaced:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CR[...]tLQ==
    server: https://12.34.56.78:6443
  name: mycluster
contexts:
- context:
    cluster: mycluster
    user: mycluster-user
  name: mycluster-user
current-context: mycluster-user
kind: Config
preferences: {}
users:
- name: mycluster-user
  user:
    client-certificate-data: LS0tLS[...]LS0=
    client-key-data: LS0tLS1[...]S0t
```
