### ISSUE TITLE
Kubelogin not supported ?

### ISSUE THREAD

**Issue by Raulster24** [kubernetes-client/csharp#1346]
**Describe the bug**
Kube config file containing kubelogin commands does not work and throws timeout exception

**Kubernetes C# SDK Client Version**
11.0.44

**Server Kubernetes Version**
1.25.5

**Dotnet Runtime Version**
net6

**KubeConfig**
```
kind: Config
preferences: {}
users:
- name: clusterUser*****
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login
      - azurecli
      - --server-id
      - *******
      command: kubelogin
      env: null
      provideClusterInfo: false
```
Please confirm if it is not supported, if not supported then is there any workaround without using kubectl proxy or generating token
