### ISSUE TITLE
Cannot query deployments from within minikube cluster

### ISSUE THREAD

**Issue by Lutando** [kubernetes-client/csharp#206]
in code in a container I have 

```
var config = KubernetesClientConfiguration.InClusterConfig()
IKubernetes client = new Kubernetes(config );
var scale = await  client.ReadNamespacedDeploymentScaleAsync("simpleapi-deployment","default");
```

```
"request": {
        "method": {
            "method": "GET"
        },
        "requestUri": "https://10.96.0.1/apis/apps/v1/namespaces/default/deployments/simpleapi-deployment/scale",
        "properties": {},
        "content": null,
        "headers": {
            "Authorization": [
                "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tZnRncnciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijg0ZTZjYmFmLTdhYzktMTFlOC05YjRiLTA4MDAyNzQwZmMwNyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.HSyaXfYM7QNoeeREBR0qf_hWov_Q7oibihURQSc0qNxedPJjWeeeJ9tCSX-nOjfdsGBmTEDzZnbOkRszAyyffzL2w-0YCFwJKYa-JccuAQt8HfMr9egqj308CU4eqQadmpjfCPw_CM57hjhP56yR_KZAjVi6I5V5Ngze0wdeHlyFod2-WDq6olNopzkoJpOQcT3lsNrQ-OwRqx-kGYGnbG_cCQYihCYFFzTaNz9PgChOYXCUOJEqHFSNxMlypK9elns1R_vuVu9FbuWWM3aH3ZnduIP9e1bxKwYnkCCxz4R082EXQEv7hDb9vlCzplzM4z3fRg3cPveCkBKtdN_e3Q"
            ],
            "User-Agent": [
                "FxVersion/4.6.26919.02",
                "k8s.Kubernetes/1.2.0.59098"
            ]
        }
    },
    "response": {
        "statusCode": 403,
        "reasonPhrase": "Forbidden",
        "content": "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"deployments.apps \\\"simpleapi-deployment\\\" is forbidden: User \\\"system:serviceaccount:default:default\\\" cannot get deployments.apps/scale in the namespace \\\"default\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"simpleapi-deployment\",\"group\":\"apps\",\"kind\":\"deployments\"},\"code\":403}\n",
        "headers": {
            "X-Content-Type-Options": [
                "nosniff"
            ],
            "Date": [
                "Thu, 11 Oct 2018 05:53:38 GMT"
            ],
            "Content-Type": [
                "application/json"
            ],
            "Content-Length": [
                "357"
            ]
        }
    }
```

It works if (from outside of k8s) i use the `KubernetesClientConfiguration.BuildConfigFromConfigFile();`  but not from inside the cluster from a container if i use `.InClusterConfig()`

**Comment by gaziqbal** [comment]
In case it's helpful to others, this is what I used on my minikube cluster to give the default service account access to crud ops on common resources.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crud-role
  namespace: default
rules:
- apiGroups: ["", "apps", "batch"]
  resources: [ "deployments", "jobs", pods", "replicasets", services" ]
  verbs: [ "create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crud-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crud-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
```
