### ISSUE TITLE
`Yaml.LoadFromString` (and others) are broken due to `namespace` keyword.

### ISSUE THREAD

**Issue by twitchax** [kubernetes-client/csharp#208]
`V1ObjectMetadata` defines the `namespace` property as follows.

```
[JsonProperty(PropertyName = "namespace")]
public string NamespaceProperty { get; set; }
```

This is likely because `namespace` is a reserved keyword in C#.  However, YamlDotNet does not respect the `JsonProperty` attribute, so these deserializers fail when they come across `namespace` in the Yaml.

The best fix would be to either use an attribute that YamlDotNet understands, or to rename this property to `Namespace`, since C# doesn't care if the `N` is capitalized.  Lastly, to avoid confusion, this property to could be marked with the `@`.

**Comment by twitchax** [comment]
`ReadOnlyProperty` on `V1VolumeMount` also suffers from this issue.

**Comment by itowlson** [comment]
Yes, the AutoRest generator which converts the k8s Swagger to C# code special-cases words that are reserved in C#, such as `namespace` or `readonly`.  I don't think we can change this without changing AutoRest, and of course it would be breaking change for consumers of the client.  I've reproduced and got a failing unit test for it, will see if I can puzzle out a fix without changing the existing library surface.  Thanks!

**Comment by twitchax** [comment]
Interestingly, I use to work with the primary AutoRest maintainer, @fearthecowboy.

@fearthecowboy, is there a graceful way to instruct AutoRest to not rename these properties?  In this case, the property names are PascalCased, so there will not be any clash in .NET code.

**Comment by fearthecowboy** [comment]
Yeah, the generator is a bit... overzealous when attempting to avoid collisions and keywords.

If you are using a [configuration file, ](https://raw.githubusercontent.com/Azure/autorest/master/Samples/1d-common-settings/readme.md) you can stick in a section :

~~~ markdown
# rename properties back to what we want them to be.
``` yaml $(csharp)
directive: 
  - reason: Tweaking the generated code.
    from: source-file-csharp
    where: $
    transform:  return $.replace(/NamespaceProperty/g, 'Namespace').replace(/ReadOnlyProperty/g,'ReadOnly');
```
~~~
