### ISSUE TITLE
What permissions are needed?

### ISSUE THREAD

**Issue by dasjestyr** [kubernetes-client/csharp#219]
I'm trying to list pods using the example but I'm getting back an error saying that I don't appropriate credentials. I'm using kube config. In terminal, I'm authenticated and I can list pods with no trouble. I verified that the machine's current context is exactly what it needs to be. Is there something else I need to do to make it work?

**Comment by tg123** [comment]
RABC? #206

**Comment by dasjestyr** [comment]
Maybe? I guess there's something else I don't understand in how this works. I'm using the same credentials with kubectl as I am with kubernetes-client. What is different to where I need to modify RBAC?

**Comment by dasjestyr** [comment]
``` yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: docker-for-desktop-cluster
- cluster:
    certificate-authority-data: <redacted>
    server: https://<redacted>
  name: gke_dasplatform-production_us-central1-a_reticle
- cluster:
    certificate-authority-data: <redacted>
    server: https://<redacted>
  name: gke_provausio-sandbox_us-west1-a_provausio-sandbox
contexts:
- context:
    cluster: docker-for-desktop-cluster
    user: docker-for-desktop
  name: docker-for-desktop
- context:
    cluster: gke_dasplatform-production_us-central1-a_reticle
    user: gke_dasplatform-production_us-central1-a_reticle
  name: gke_dasplatform-production_us-central1-a_reticle
- context:
    cluster: gke_provausio-sandbox_us-west1-a_provausio-sandbox
    user: gke_provausio-sandbox_us-west1-a_provausio-sandbox
  name: gke_provausio-sandbox_us-west1-a_provausio-sandbox
current-context: gke_dasplatform-production_us-central1-a_reticle
kind: Config
preferences: {}
users:
- name: docker-for-desktop
  user:
    client-certificate-data: <redacted>
    client-key-data: <redacted>
- name: gke_dasplatform-production_us-central1-a_reticle
  user:
    auth-provider:
      config:
        access-token: <redacted>
        cmd-args: config config-helper --format=json
        cmd-path: /Users/jstafford/google-cloud-sdk/bin/gcloud
        expiry: 2018-11-03T18:39:26Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_provausio-sandbox_us-west1-a_provausio-sandbox
  user:
    auth-provider:
      config:
        access-token: <redacted>
        cmd-args: config config-helper --format=json
        cmd-path: /Users/jstafford/google-cloud-sdk/bin/gcloud
        expiry: 2018-09-27 06:54:22
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp

```
