### ISSUE TITLE
kubeconfig handling is overly sensitive

### ISSUE THREAD

**Issue by colemickens** [kubernetes-client/csharp#24]
For example, this is a valid config file that kubectl accepts, but this client can not parse into KubernetesClientCredentials:

```
apiVersion: v1
kind: Config
clusters:
- name: colemick1
  cluster:
    server: https://colemick1-api.westus.cloudapp.azure.com:443
    certificate-authority-data: <redacted>
users:
- name: kubelet
  user:
    client-certificate-data: <redacted>
    client-key-data: <redacted>
contexts:
- context:
    cluster: colemick1
    user: kubelet
```

I had to:
1. name the context
2. actually set the active context in the kubeconfig

I'm not sure it's technically a well-formed kubeconfig, but I figure if `kubectl` accepts it, that this client should too.
