### ISSUE TITLE
unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

### ISSUE THREAD

**Issue by richardgragasin** [kubernetes-client/csharp#285]
I'm using  
`var config = KubernetesClientConfiguration.InClusterConfig();`
for getting the cluster config inside of minikube. 

I also created a service account to avoid 403: forbidden when calling kubernetes API. 
but upon getting the cluster config my c# application throws and exception 

**k8s.Exceptions.KubeConfigException: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined**

![image](https://user-images.githubusercontent.com/13230343/57676005-14382680-7656-11e9-91a1-266962015f2d.png)

Any idea why i get this kind of issue? 

serviceAccount.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
automountServiceAccountToken: false
```

deployment.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 ...
spec:
  ...
  template:
    metadata:
    ...
    spec:
      serviceAccountName: build-robot
      automountServiceAccountToken: false
```
