### ISSUE TITLE
ClusterRoleBinding and RoleBinding creation 'BadRequest'

### ISSUE THREAD

**Issue by Bliamoh** [kubernetes-client/csharp#286]
I'm trying to use the Kubernetes Client to create ClusterRoleBinding and RoleBinding with YAML files, however I always get a 'BadRequest' response. Here is my code:

```
var kubernetesClientConfig = KubernetesClientConfiguration.InClusterConfig();
// var kubernetesClientConfig = KubernetesClientConfiguration.BuildConfigFromConfigFile(); // Use this when working locally
IKubernetes client = CreateKuberneteClient();

try
{
	switch (ResourceType)
	{
		case KubernetesResource.ClusterRole:
			client.CreateClusterRole(Yaml.LoadFromString<V1ClusterRole>(YamlToDeploy));
			break;
		case KubernetesResource.ClusterRoleBinding:
			client.CreateClusterRoleBinding(Yaml.LoadFromString<V1ClusterRoleBinding>(YamlToDeploy));
			break;
		case KubernetesResource.Deployment:
			client.CreateNamespacedDeployment(Yaml.LoadFromString<V1Deployment>(YamlToDeploy), _config.DockerImagesDefaultNamespace);
			break;
		case KubernetesResource.Pod:
			client.CreateNamespacedPod(Yaml.LoadFromString<V1Pod>(YamlToDeploy), _config.DockerImagesDefaultNamespace);
			break;
		case KubernetesResource.Role:
			client.CreateNamespacedRole(Yaml.LoadFromString<V1Role>(YamlToDeploy), _config.DockerImagesDefaultNamespace);
			break;
		case KubernetesResource.RoleBinding:
			client.CreateNamespacedRoleBinding(Yaml.LoadFromString<V1RoleBinding>(YamlToDeploy), _config.DockerImagesDefaultNamespace);
			break;
		case KubernetesResource.ServiceAccount:
			client.CreateNamespacedServiceAccount(Yaml.LoadFromString<V1ServiceAccount>(YamlToDeploy), _config.DockerImagesDefaultNamespace);
			break;
	}
}
catch (Exception ex)
{
	Logger.Error(ex.Message);
}
```

And here are my YAML files:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-client-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: kubernetes-client-cr
rules:
- apiGroups: ["", "extensions", "apps", "batch", "rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings", "deployments", "pods", "roles", "rolebindings", "serviceaccounts"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-client-crb
subjects:
  - kind: ServiceAccount
    name: kubernetes-client-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: kubernetes-client-cr
  apiGroup: rbac.authorization.k8s.io
```

So as you can see, I'm trying to create some Kubernetes resources according to a resource type and a YAML file. When I create the above ServiceAccount and ClusterRole (or even if it's juste a Role), everything is working fine. But the creation of the ClusterRoleBinding (or juste ClusterRole) gives me this 'BadRequest' reply. Here is the stack trace:  

```
Error Message: Operation returned an invalid status code 'BadRequest'

Stack Trace: at k8s.Kubernetes.CreateClusterRoleBindingWithHttpMessagesAsync(V1ClusterRoleBinding body, String dryRun, String fieldManager, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
 at k8s.KubernetesExtensions.CreateClusterRoleBindingAsync(IKubernetes operations, V1ClusterRoleBinding body, String dryRun, String fieldManager, String pretty, CancellationToken cancellationToken)
 at k8s.KubernetesExtensions.CreateClusterRoleBinding(IKubernetes operations, V1ClusterRoleBinding body, String dryRun, String fieldManager, String pretty)
 at Website.OnPostDeployYaml() in C:\Users\user1\Website\Pages\Cluster\Test.cshtml.cs:line 151
```

I tried with Kubernetes through Docker for Windows using BuildConfigFromConfigFile() and within an Azure cluster with InClusterConfig() but I get this response in both configurations and since every other Kubernetes resources manage to be created, I don't think it's a problem with my configuration.  
 The YAML files are working fine when I'm using them with a 'kubectl create -f file.yaml' or 'kubectl apply -f file.yaml' command so I don't think that there is an issue with my ClusterRoleBinding declaration.
