### ISSUE TITLE
RBAC Requirments

### ISSUE THREAD

**Issue by s-leonard** [kubernetes-client/csharp#289]
This is more of documentation issue I guess. 

Your simple example of `var list = client.ListNamespacedPod("default"); `
works remotely using the `BuildConfigFromConfigFile()` config, but when I'm running this from inside a POD using` InClusterConfig()` I get " Operation returned an invalid status code 'Forbidden' "
I've tried adding something like this

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
```

to give permissions, but I don't know what the `ListNamespacedPod()` function is doing behind the scenes or how to give the right permission. Is there anyway of finding this?
