### ISSUE TITLE
intorstring wrong serialization.

### ISSUE THREAD

**Issue by GlennArens** [kubernetes-client/csharp#299]
if you try to assign an int to the targetport variable in V1Service it get serialized as 
```
apiVersion: v1
kind: Service
metadata:
  labels: &o0
    app: zoneapi
  name: zoneapi
spec:
  ports:
  - port: 3000
    targetPort:
      value: 3000
  selector: *o0---
apiVersion: apps/v1
```
it should be serialized as
```
apiVersion: v1
kind: Service
metadata:
  labels: &o0
    app: zoneapi
  name: zoneapi
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector: *o0---
apiVersion: apps/v1
```

Code to generate issue:
```
 Dictionary<string, string> labels = new Dictionary<string, string>
                                                {
                                                    {"app", "test"}
                                                };

V1Service service = new V1Service
                                {
                                    Kind = "Service",
                                    Metadata = new V1ObjectMeta(labels: labels, name: "test-svc"),
                                    ApiVersion = "v1",
                                    Spec = new V1ServiceSpec
                                           {
                                               Selector = labels,
                                               Ports = new List<V1ServicePort>
                                                       {
                                                           new V1ServicePort
                                                           {
                                                               Port = 3000,
                                                               TargetPort = 3000
                                                           }
                                                       }
                                           }
                                };
```
