### ISSUE TITLE
[Question] Can I do kubectl apply using this client library?

### ISSUE THREAD

**Issue by weng271190436** [kubernetes-client/csharp#304]
I see a lot of Patch* methods. Can I use those as "kubectl apply"?

**Comment by brendandburns** [comment]
No, kubectl apply was traditionally client side.

This has moved to server side (https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply)

But it only hit beta in 1.16.

When we regenerate for 1.16 we should be able to do it in the library.

**Comment by mszynka** [comment]
@brendandburns can we "regenerate" and get access to "kubectl apply" in the library?

**Comment by Stijn98s** [comment]
Is there any other option to apply a yaml file with this kubernetes client?

**Comment by eosfor** [comment]
+1 to the question.

**Comment by brendandburns** [comment]
You can use 'create' it's not the same as 'apply' but it will create resources.

**Comment by Athosone** [comment]
Do you have a suggestion then if I must apply a file (e.g from the helm controller made by rancher) ?
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
```
