### ISSUE TITLE
While providing certificates, client keeps using anonymous auth

### ISSUE THREAD

**Issue by mateusz-lipowski** [kubernetes-client/csharp#319]
I'm attempting to replace token auth with certificates, but API is responding with `{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:anonymous\" cannot list resource \"pods\" in API group \"\" in the namespace \"domvi-test-appservice\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}`.

I'm sure that cerificate is valid and RBAC is properly configured, because kubectl works without problems and RoleBinding is the same as for token (which works properly).

I've tried multiple configurations: passing cert file paths, using raw base64 certs, reading kubeconfig that works for kubectl, all with the same result.

My current test code look like this (inspired by your AuthTests.cs):
```
var crtPath = "C:\\Users\\mateuszl\\Desktop\\cert\\domvi-test-appservice.crt";
var keyPath = "C:\\Users\\mateuszl\\Desktop\\cert\\domvi-test-appservice.key";

var config = new KubernetesClientConfiguration
{
	Host = context.Host,
	Namespace = "domvi-test-appservice",
	Username = "integration-test",
	ClientCertificateFilePath = crtPath,
	ClientKeyFilePath = keyPath,
	SkipTlsVerify = true
};

kubernetes = new Kubernetes(config);

kubernetes.ListNamespacedPod("domvi-test-appservice"); // Throws HttpOperationException
```

**Comment by brendandburns** [comment]
Can you try loading the `${KUBECONFIG}` file that works for `kubectl` using the `KuberentesClientConfiguration.BuildConfigFromConfigFile(...)` function?

If that works, then you need to figure out what is different between the code that you have above and the code that is called in that function.

If that _doesn't_ work, then please file a new issue, because we should be able to load any file that works with `kubectl`

Thanks!

**Comment by mateusz-lipowski** [comment]
Using `KubernetesClientConfiguration.BuildConfigFromConfigFile` gives exactly the same result. I guess that config loading works properly and certificate is the only issue. I also tried many other ways to load config, like putting config yaml in string and reading it or using `KubernetesClientConfiguration.BuildConfigFromConfigObject` with manually populated object.

My config is essentially copy-paste of the one generated by kubeadm, with replaced certs and namespace. That's how it looks:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: Skipped Base64 CA Cert
    server: https://10.1.0.61:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: domvi-test-appservice
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: Skipped Base64 Cert
    client-key-data: Skipped Base64 Key
```

Sould I really create a new issue? That would be just an exact copy of this one.
