### ISSUE TITLE
Configuration deserialization fail when using EKS configuration file

### ISSUE THREAD

**Issue by rkttu** [kubernetes-client/csharp#340]
When I try to load EKS modified configuration file with the below code, Yaml parser exception throwed.

**Source code**

```csharp
var config = KubernetesClientConfiguration.BuildConfigFromConfigFile(
	kubeconfigPath: @"\\wsl$\Ubuntu-18.04\home\rkttu\.kube\config");
```

**YAML file**

```yaml
...
users:
- name: arn:aws:eks:ap-northeast-1:...:cluster/eagle
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - ap-northeast-1
      - eks
      - get-token
      - --cluster-name
      - eagle
      command: aws
      env:
      - name: AWS_PROFILE
        value: example
```
