### ISSUE TITLE
Port-forward strange..

### ISSUE THREAD

**Issue by MortenMeisler** [kubernetes-client/csharp#343]
There's something not quite working in the [port-forward example](https://github.com/kubernetes-client/csharp/blob/master/examples/portforward/PortForward.cs), does anyone have something that is equivalent of doing this:
`kubectl port-forward jupyter-notebook-pod-123 8888:8888 -n default` ?

When I try to launch a jupyter workbook pod the UI is not fully loaded, ex. you cannot make a new Python3 notebook. 

I checked #297, and it seemed to work if I added `listener.Close();` using @gittadesushil suggestion. But then after a short while the connection seems to break down.

**To replicate:**
Use the following yaml-file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: minimal-notebook
        image: jupyter/minimal-notebook:latest
        ports:
        - containerPort: 8888
```
Apply it:
`kubectl apply -f jupyter.yaml`

After fully deployed, check the logs:
`kubectl logs jupyter-notebook-pod-123` 

Note down the URI and then do a port-forward:
`kubectl port-forward jupyter-notebook-pod-123 8888:8888 -n default`

This works, but the example not quite. You have to replace the hardcoded port-numbers with 8888 in the example.

Thanks
