### ISSUE TITLE
Failure to parse AWS generated kube config

### ISSUE THREAD

**Issue by seanamosw** [kubernetes-client/csharp#396]
I saw the initial implementation for supporting the `user/exec` config was done in https://github.com/kubernetes-client/csharp/pull/359

However, it appears that it is still unable to parse the `exec/env` section.

This appears to be how the model is specified in https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/KubeConfigModels/ExternalExecution.cs

```csharp
        [YamlMember(Alias = "env")]
        public IDictionary<string, string> EnvironmentVariables { get; set; }
```

That would parse yaml with this format:
```yaml
env:
  name1: value1
  name2: value2
```

However the actual format is:
```yaml
env:
   - name: name1
     value: value1
   - name: name2
     value: value2
```
I believe this needs to at least be changed to something like this:

```csharp
        [YamlMember(Alias = "env")]
        public IList<IDictionary<string, string>> EnvironmentVariables { get; set; }
```

Might want to further change it to something like:
```csharp
        public IList<NameValuePair> EnvironmentVariables { get; set; }
```
