### ISSUE TITLE
external exec failed due to: The system cannot find the file specified.

### ISSUE THREAD

**Issue by Rimobul** [kubernetes-client/csharp#478]
I have a Windows 10 PC with WSL 2. I am running my `kubectl` from the WSL 2 system. I was trying to do a simple console app using the **kubernetes-client** to list all my namespaces. Here is my code:

```
using System;
using System.IO;
using System.Threading.Tasks;
using k8s;

namespace MyProject
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var path = @"\\wsl$\Ubuntu-20.04\home\myname\.kube\my-config";
            var exists = File.Exists(path);
            Console.WriteLine($"File exists {exists}");

            var fi = new FileInfo(path);
            var config = await KubernetesClientConfiguration.BuildConfigFromConfigFileAsync(fi);

            using (var client = new Kubernetes(config))
            {
                var namespaces = await client.ListNamespaceAsync();
                foreach (var item in namespaces.Items)
                {
                    Console.WriteLine(item.Metadata.Name);
                }
            }
        }
    }
}
```

And here is the content of the *my-config* file:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <hash>
    server: <url>
  name: <EKS cluster ARN>
contexts:
- context:
    cluster: <EKS cluster ARN>
    user: <EKS cluster ARN>
  name: <EKS cluster ARN>
current-context: <EKS cluster ARN>
kind: Config
preferences: {}
users:
- name: <EKS cluster ARN>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - EKS-Cluster
      command: aws
```

When executing the code from WSL, I get a *Null reference exception* at the start of the `foreach` loop, because the variable `namespaces` is `null`. When running from Windows, I get the following output (note the `File exists True` output at the start):

 ```
File exists True
Unhandled exception. k8s.Exceptions.KubeConfigException: external exec failed due to: The system cannot find the file specified.
   at k8s.KubernetesClientConfiguration.ExecuteExternalCommand(ExternalExecution config)
   at k8s.KubernetesClientConfiguration.SetUserDetails(K8SConfiguration k8SConfig, Context activeContext)
   at k8s.KubernetesClientConfiguration.InitializeContext(K8SConfiguration k8SConfig, String currentContext)
   at k8s.KubernetesClientConfiguration.GetKubernetesClientConfiguration(String currentContext, String masterUrl, K8SConfiguration k8SConfig)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFileAsync(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
   at MyProject.Program.Main(String[] args) in C:\repos\myproject\src\MyProject\Program.cs:line 17
   at MyProject.Program.<Main>(String[] args)
```

I have tried moving the config file also to Windows file system (`C:\Users\myname\.kube`), but I got the same error. Am I doing something wrong? Or is this a bug?

**Comment by tg123** [comment]
it is trying to exec `aws` as defined in `command: aws`

**Comment by brendandburns** [comment]
I think that you need to do one of two things:

1) Run this code under dotnet-core and in WSL2 rather than Windows (e.g. run it with dotnet for Linux)

2) change the `command` field in your kubeconfig file to look like:

```yaml
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - aws
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - EKS-Cluster
      command: wsl
```

Which will use the `wsl` command line tool to invoke the command inside a wsl environment.

It's probably also possible to install the `aws` tool in Windows but I'm not super familiar with it.
