### ISSUE TITLE
Timeout running ListNamespacedServiceAsync/ ListNamespacedService in Cluster, not locally

### ISSUE THREAD

**Issue by kieronlanning** [kubernetes-client/csharp#569]
Running ListNamespacedServiceAsync (or ListNamespacedService) works locally, but fails with a timeout when running from within the cluster.

Using the Async version, here's what I currently have:

```
const int maxServices = 20;

var config = KubernetesClientConfiguration.BuildDefaultConfig();

using var client = new Kubernetes(config);
var serviceResponse = await client.ListNamespacedServiceAsync(openAPISettings.Value.k8s.Namespace, labelSelector: openAPISettings.Value.k8s.LabelSelector, limit: maxServices, cancellationToken: cts.Token);
var services = new List<V1Service>(serviceResponse.Items);

logger.LogInformation("Returned {serviceCount} services.", services.Count);

var continueParameter = serviceResponse.Continue();
while (continueParameter != null)
{
	logger.LogInformation("In continuation.");

	serviceResponse = await client.ListNamespacedServiceAsync(openAPISettings.Value.k8s.Namespace, labelSelector: openAPISettings.Value.k8s.LabelSelector, limit: maxServices, continueParameter: continueParameter, cancellationToken: cts.Token);
	services.AddRange(serviceResponse.Items);

	logger.LogInformation("Returned {serviceCount} additional services, totaling {total}.", serviceResponse.Items.Count, services.Count);

	continueParameter = serviceResponse.Continue();
}
```

This used to work, I think it may have stopped working after an AKS upgrade, but I'm not sure when.

The YAML for the roles looks like this:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-api-account
  namespace: strata2-dev
automountServiceAccountToken: false
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: strata2-dev
  name: open-api-service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-api-service-reader
  namespace: strata2-dev
subjects:
  - kind: ServiceAccount
    name: open-api-account
    namespace: strata2-dev
roleRef:
  kind: ClusterRole
  name: open-api-service-reader
  apiGroup: rbac.authorization.k8s.io
```
