### ISSUE TITLE
Env with valueFrom and fieldRef

### ISSUE THREAD

**Issue by galvesribeiro** [kubernetes-client/csharp#597]
Hey folks!

How can I create the following env used in a pod definition?

```yaml
- name: MY_POD_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
```

I'm asking this because I see no clear object in the `k8s.Models` namespaces that would allow to create an envVar for a pod with the value coming from a field like in this example, the `status.podIP`.

Can someone tell me if that is supported and how?

Thank you!
