### ISSUE TITLE
Serialization/Deserialization issue

### ISSUE THREAD

**Issue by cdavernas** [kubernetes-client/csharp#619]
## How to reproduce

Parse the yaml of a CRD that specify 'x-kubernetes-preserve-unknown-fields' field, and try to create it on K8s using the client.

```yaml
#crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflow-instances.synapse.io
spec:
  scope: Namespaced
  names:
    plural: workflow-instances
    singular: workflow-instance
    kind: WorkflowInstance
  group: synapse.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                input:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
```

```csharp
var yaml = File.ReadAllText("crd.yaml");
var crd = Yaml.LoadFromString(yaml);
await this.Kubernetes.CreateCustomResourceDefinitionAsync(crd, cancellationToken: cancellationToken);
```

## Expected behavior

Kubernetes creates the CRD, with 'x-kubernetes-preserve-unknown-fields' set to true

## Actual behavior

Kubernetes returns a 400 bad request with the following content:

```json
{
   "kind":"Status",
   "apiVersion":"v1",
   "metadata":{
      
   },
   "status":"Failure",
   "message":"CustomResourceDefinition in version \"v1\" cannot be handled as a CustomResourceDefinition: v1.CustomResourceDefinition.Spec: v1.CustomResourceDefinitionSpec.Versions: []v1.CustomResourceDefinitionVersion: v1.CustomResourceDefinitionVersion.Schema: v1.CustomResourceValidation.OpenAPIV3Schema: v1.JSONSchemaProps.Properties: v1.JSONSchemaProps.Required: []string: Properties: v1.JSONSchemaProps.Type: Properties: v1.JSONSchemaProps.Type: Items: unmarshalerDecoder: json: cannot unmarshal string into Go struct field JSONSchemaProps.x-kubernetes-preserve-unknown-fields of type bool, error found in #10 byte of ...|         },\r\n       |..., bigger context ...|unknown-fields\": \"true\"\r\n                        },\r\n                        \"type\": \"array\"\r\n      |...",
   "reason":"BadRequest",
   "code":400
}
```

## Notes

I tried deserializing the above yaml, where `x-kubernetes-preserve-unknown-fields: true` is clearly defined as a boolean. If I serialize the resulting V1CustomResourceDefinition back to Yaml, using `Yaml.SaveToString(myYaml)`, here's the result for the field:

`x-kubernetes-preserve-unknown-fields: "True"`

I believe this happens because the 'V1JSONSchemaProp's PreserveUnknownFields` is serialized/deserialized as string instead of boolean.
