### ISSUE TITLE
Getting "Unathorized" response when kubectl is working? 

### ISSUE THREAD

**Issue by amsoedal** [kubernetes-client/csharp#624]
Hi, we have a customer who's been reporting that our CLI returns "unathorized" when they try to interact with their cluster, but when they use other kubernetes tools (kubectl, or the node kubernetes client) that everything works fine. Since our CLI relies on the c# kubernetes client, is there a possible issue related to this? They say they doesn't have access to the default namespace, but we're trying to list pods in a specified (non-default) namespace on their behalf.

**Comment by tg123** [comment]
`var config = KubernetesClientConfiguration.BuildDefaultConfig();` to have same config loading pattern as kubectl

**Comment by brendandburns** [comment]
It's always possible that we don't support some authentication method. Can you paste the details of the kubeconfig file (with secrets redacted, obviously)

**Comment by jarrett-confrey** [comment]
@brendanburns i am the one whos seeing the issue, this is what my kubeeconfig looks like
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: ...
  name: ...
contexts:
- context:
    cluster: ...
    namespace: ...
    user: ...
  name: ...
current-context: ...
kind: Config
preferences: {}
users:
- name: ...
  user:
    auth-provider:
      config:
        client-id: gangway
        client-secret: ...
        id-token: ...
        idp-issuer-url: https://dex...
        refresh-token: ...
      name: oidc
```
