### ISSUE TITLE
Forbidden error with every request

### ISSUE THREAD

**Issue by justinmchase** [kubernetes-client/csharp#641]
I'm just trying to connect to my local kubernetes cluster on my machine. I have the current context set to be `docker-desktop`:
![Screen Shot 2021-05-29 at 1 19 58 PM](https://user-images.githubusercontent.com/10974/120080942-97cbe100-c080-11eb-9a76-54e38dddd851.png)

And I can use `kubectl` without any errors:
<img width="457" alt="Screen Shot 2021-05-29 at 1 21 12 PM" src="https://user-images.githubusercontent.com/10974/120080987-c21d9e80-c080-11eb-876c-a215d90b8f9e.png">

I just have this very minimal example code:
```cs
var config = KubernetesClientConfiguration.BuildConfigFromConfigFile();
var client = new Kubernetes(config);
var ns = await client.ReadNamespaceAsync("default");
```

Which ends up throwing a forbidden error:
![Screen Shot 2021-05-29 at 1 17 00 PM](https://user-images.githubusercontent.com/10974/120080925-8387e400-c080-11eb-94dd-75de430fb94e.png)

What could be going wrong? 

I am on a mac and I'm using dotnet core 5.0 in visual studio code.

The config seems to be setup right:
![Screen Shot 2021-05-29 at 1 24 25 PM](https://user-images.githubusercontent.com/10974/120081126-6dc6ee80-c081-11eb-902c-5814b786c448.png)

**Comment by tg123** [comment]
if kubectl works well, likely a bug in mac env, let me find a mac to test it

**Comment by brendandburns** [comment]
What does your kubeconfig file look like ($HOME/.kube/config)?

Please post that file (with secrets removed, obviously) I suspect that there is some unsupported authentication going on.

**Comment by brendandburns** [comment]
You could try SkipTlsVerify to true. That's insecure, but if it works it would show that we have a certificate loading problem (vs a client-cert problem, etc)

**Comment by justinmchase** [comment]
Here's my config, with some redactions:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: <redacted>
    client-key-data: <redacted>
```
