### ISSUE TITLE
Forbidden 403 for some methods

### ISSUE THREAD

**Issue by dk-do** [kubernetes-client/csharp#651]
Good morning everybody!

I have a problem with some requests which throw a 403 forbidden error.

While methods like:

- ListNamespacedPodAsync
- ReadNamespaceAsync
- ReadNamespacedPodAsync

are working fine.

The following throw a http 403:

- ReadNamespacedPodStatusAsync
- ReadNamespacedPodLogAsync

Anyone an idea?

I use the Visual Studio Bridge to Kubernetes which is connected to a K8S Cluster in v1.18.3 with three masters and six worker nodes (C#, .NET Core 5.x). The underlying OS is Ubuntu 18.04.5 LTS.

The clusterrole is:

```
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - pods
  - namespaces
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumes
  - componentstatuses
  - resourcequotas
  - persistentvolumeclaims
  - endpoints
  verbs:
  - get
  - list
  - watch
  - head
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
```
