### ISSUE TITLE
CRD spec serialization issue

### ISSUE THREAD

**Issue by shihaohems** [kubernetes-client/csharp#714]
## Issue

Array in CRD spec not get deserialized into `V1JSONSchemaProps` as expected. As a result, non-string properties are deserialized into strings.

## How to reproduce

- Create a CRD yaml with array in spec containing non-string property
- Deserialize the yaml into `V1CustomResourceDefinition`
- Serialize the `V1CustomResourceDefinition` object

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: foobar.foo.bar.com
spec:
  group: foo.bar.com
  names:
    kind: FooBar
    listKind: FooBarList
    plural: foobars
    singular: foobar
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              foo:
                items:
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                    valueFrom:
                      properties:
                        bar:
                          properties:
                            port:
                              anyOf:
                              - type: integer
                              - type: string
                              x-kubernetes-int-or-string: true
                          type: object
                      type: object
                  required:
                  - name
                  type: object
                type: array
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```
```c#
var yaml = File.ReadAllText("foobar.yaml");
var crd = Yaml.LoadFromString<V1CustomResourceDefinition>(yaml);
Console.WriteLine(Yaml.SaveToString(crd));
```

## Expected behavior

Output content is semantically equal to the original yaml. 

## Actual behavior

` x-kubernetes-int-or-string: "true"`
