### ISSUE TITLE
'Refresh not supported' occasionally

### ISSUE THREAD

**Issue by LeiYangGH** [kubernetes-client/csharp#764]
Now my `~/.kube/config` has only one cluster, the line of code works well:
```csharp
var config = KubernetesClientConfiguration.BuildDefaultConfig();
```
But occasionally report 'Refresh not supported' error.
Looks very strange to me. I don't know what need to be refereshed. Maybe this errror message comes from azure side and not related to client library. But could the error message be enhanced more friendly?

**double checked:**

1. tried deleting `~/.kube/cache` and `~/.kube/http-cache` folder first, same issue.
2. `kubectl` always worked.

**Stack trace**:

> k8s.Exceptions.KubeConfigException
>   HResult=0x80131500
>   Message=Refresh not supported.
>   Source=KubernetesClient
>   StackTrace:
>    at k8s.KubernetesClientConfiguration.RenewAzureToken(String tenantId, String clientId, String apiServerId, String refresh)
>    at k8s.KubernetesClientConfiguration.SetUserDetails(K8SConfiguration k8SConfig, Context activeContext)
>    at k8s.KubernetesClientConfiguration.InitializeContext(K8SConfiguration k8SConfig, String currentContext)
>    at k8s.KubernetesClientConfiguration.GetKubernetesClientConfiguration(String currentContext, String masterUrl, K8SConfiguration k8SConfig)
>    at k8s.KubernetesClientConfiguration.<BuildConfigFromConfigFileAsync>d__12.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
>    at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(String kubeconfigPath, String currentContext, String masterUrl, Boolean useRelativePaths)
>    at k8s.KubernetesClientConfiguration.BuildDefaultConfig()

i uploaded the `config` file.
[config.txt](https://github.com/kubernetes-client/csharp/files/7851436/config.txt)
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2RENDQX
    server: https://oc-k8s-app-1-dev-use2-aks-somehash.hcp.eastus2.azmk8s.io:443
  name: oc-k8s-app-1-dev-use2-aks
contexts:
- context:
    cluster: oc-k8s-app-1-dev-use2-aks
    user: clusterUser_oc-k8s-app-1-dev-use2-aks_oc-k8s-app-1-dev-use2-aks
  name: oc-k8s-app-1-dev-use2-aks
current-context: oc-k8s-app-1-dev-use2-aks
kind: Config
preferences: {}
users:
- name: clusterUser_oc-k8s-app-1-dev-use2-aks_oc-k8s-app-1-dev-use2-aks
  user:
    auth-provider:
      config:
        access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1yNS1BVWli
        apiserver-id: someguid
        client-id: someguid
        config-mode: "1"
        environment: AzurePublicCloud
        expires-in: "4023"
        expires-on: "1641961860"
        refresh-token: 0.ATcA14o_NuMbBU-Ka0lVdW_i9iD5-oAIGVJLte-o577fxno3ADQ.
        tenant-id: someguid
      name: azure
```
