### ISSUE TITLE
C# The SSL connection could not be established

### ISSUE THREAD

**Issue by michelkamp** [kubernetes-client/csharp#795]
### **### Description:**
I want to use the kubernetes client in C# to assess a Azure AKS cluster.
Running .Net Core 3.1 (also tried  .Net 6)

### Problem:
At:  var namespaces = client.ListNamespace();
I get the error:
**_The SSL connection could not be established, see inner exception._**
**_The message received was unexpected or badly formatted._**

### Investigation:
Using kubectl gives me correct output so the kube config must be correct (?):
`
c:\kubectl.exe get pods --kubeconfig="C:\Users\michel\.kube\config"
`
NAME                         READY   STATUS    RESTARTS   AGE
mysql-7798-4zj2t       1/1     Running   0          24d
webserver-5d99-d4pdz   1/1     Running   0          24d
wordpress-69f4f-rfgcn   1/1     Running   0          24d

### The code used:

```
 var config = KubernetesClientConfiguration.BuildConfigFromConfigFile(@"C:\Users\michel\.kube\config");

 var client = new Kubernetes(config);

 var namespaces = client.ListNamespace();
```

the kube config (masked):

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JS.......
    server: https://kubernetessdemo01-dns-8.hcp.westeurope.azmk8s.io:443
  name: kubernetessdemo01
contexts:
- context:
    cluster: kubernetessdemo01
    user: clusterUser_kubernetes_kubernetessdemo01
  name: kubernetessdemo01
current-context: kubernetessdemo01
kind: Config
preferences: {}
users:
- name: clusterUser_kubernetes_kubernetessdemo01
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t......
    client-key-data: LS0tLS1CRUdJTiBSU0EgU.......
    token: 6872990f......

```

**Anybody an idea ? i searched a lot on google but can't find the solution.**

Thanks!
