### ISSUE TITLE
BuildConfigFromConfigFile explanation missing

### ISSUE THREAD

**Issue by mac2000** [kubernetes-client/csharp#91]
Hello, I'm trying to run code copied from examples but got `Unhandled Exception: k8s.Exceptions.KubeConfigException: User: X does not have appropriate auth credentials in kubeconfig`

Can not find instructions in readme how should we run code locally agains google cloud kubernetes

I do have `~/.kube` and commands like `kubectl get pods` are working as expected

**Comment by tg123** [comment]
#24 
cloud you please paste your config for debug?

the sdk should have same behavior as kubectl

**Comment by mac2000** [comment]
do you mean `.kube/config` here you go:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ****************************=
    server: https://X.X.X.X
  name: gke_project_id_europe-west1-b_cluster
contexts:
- context:
    cluster: gke_project_id_europe-west1-b_cluster
    user: gke_project_id_europe-west1-b_cluster
  name: gke_project_id_europe-west1-b_cluster
current-context: gke_project_id_europe-west1-b_cluster
kind: Config
preferences: {}
users:
- name: gke_project_id_europe-west1-b_cluster
  user:
    auth-provider:
      config:
        access-token: ******************************
        cmd-args: config config-helper --format=json
        cmd-path: /Users/mac/dev/google-cloud-sdk/bin/gcloud
        expiry: 2018-02-04T12:51:26Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

I just replaced some thing that might be important, hope that helps. Feel free to ask me for any additional information if needed
